export default {
  // sspELI: 'SourceSansPro-ExtraLightItalic',
  // sspSBI: 'SourceSansPro-SemiBoldItalic',
  // sspLI: 'SourceSansPro-LightItalic',
  // sspEL: 'SourceSansPro-ExtraLight',
  // sspBI: 'SourceSansPro-BoldItalic',
  // sspSB: 'SourceSansPro-SemiBold',
  // sspI: 'SourceSansPro-Italic',
  // sspL: 'SourceSansPro-Light',
  // sspB: 'SourceSansPro-Bold',
  // sspR: 'SourceSansPro-Regular',
  // // ---- Segoeui
  // sgBI: 'SegoeUI-BoldItalic',
  // sgSL: 'SegoeUI-Semilight',
  // sgI: 'SegoeUI-Italic',
  // sgL: 'SegoeUI-Light',
  // sgB: 'SegoeUI-Bold',
  // sg: 'SegoeUI',
  // robo: 'Roboto',
  // roboM: 'Roboto-Medium',
  // roboB: 'Roboto-Bold',
};
